# Generated by Django 2.0.8 on 2018-09-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
