# Generated by Django 2.0.8 on 2018-09-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
    ]
