# Generated by Django 2.0.8 on 2018-09-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
