# Generated by Django 2.0.8 on 2018-10-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181009_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='per',
            name='F',
        ),
        migrations.RemoveField(
            model_name='per',
            name='estado',
        ),
        migrations.AlterField(
            model_name='per',
            name='data_nasc',
            field=models.DateField(),
        ),
    ]
