# Generated by Django 2.0.8 on 2018-10-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181009_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='sexo',
            field=models.CharField(choices=[('0', 'Masculino'), ('1', 'Feminino')], max_length=1, null=True),
        ),
    ]
