# Generated by Django 2.0.8 on 2018-10-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_per_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
    ]
